id: AB0728670
title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:17:08.147807
  last_modified_at: 2022-03-01 02:17:08.147810
