id: AB0728670
title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:17:08.145214
  last_modified_at: 2022-03-01 02:17:08.145223
